server:
  port: 8090

spring:
  application:
    name: EUREKA-CLIENT

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

