server:
  port: 0

spring:
  application:
    name: STREAM-SINK
  cloud:
    stream:
      bindings:
        input:
          destination: topic
          group: group1
        output:
          destination: topic
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

