server:
  port: 10000

eureka:
  instance:
    appname: eureka-server
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      - http://${eureka.instance.hostname}:${server.port}
