server:
  port: 9000

spring:
  application:
    name: EUREKA-SERVER
  boot:
    admin:
      client:
        url: http://localhost:9100
        instance:
          prefer-ip: true
        username: admin
        password: admin

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 10


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



